### ISSUE TITLE
exporting note 

### ISSUE THREAD

**Issue by pfkdesign** [ignatandrei/ppt2reveal#1]
Hi , 
I just wonder how to export also together with slides the respective notes ?

Best regards
Peter

**Comment by ignatandrei** [comment]
See 
max = p.Slides.Count
Here you can access the notes and export them.

**Comment by pfkdesign** [comment]
Danke ;)

**Comment by ignatandrei** [comment]
Could you please show the code used ? I may want to put on my code...
